title: Testing Jekyll

email: jbkunst@gmail.com

layout: post

permalink: /:categories/:title/

baseurl: ""

url: "jbkunst.github.io"

twitter_username: jbkunst

github_username:  jbkunst

markdown: kramdown
