title: Jkunst
tagline: R, Data & Code

author:
  name: Joshua Kunst
  email: jbkunst@gmail.com
  twitter: jbkunst
  github: jbkunst
  
include: ['_pages']
  
layout: post
permalink: /:categories/:title/

url: http://jkunst.com

markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
